### ISSUE TITLE
Broadcast Task

### ISSUE THREAD

**Issue by dragonwocky** [BoxOfDevs/BoxOfBits#10]
Trying to add a broadcast feature which sends a random message out of 5 different ones you can set in messages.yml, and you can set the amount of seconds inbetween each broadcast in config.yml. Anyone have any idea how to do this?

**Comment by dragonwocky** [comment]
Basically like SimpleMessages broadcasting features by @Dutok

**Comment by dragonwocky** [comment]
Ok, I finished adding the task, can someone check if I have done it right?

**Comment by Ad5001** [comment]
I'll check :)

**Comment by dragonwocky** [comment]
Ok thanx
