### ISSUE TITLE
Task Execution Problem

### ISSUE THREAD

**Issue by dragonwocky** [BoxOfDevs/BoxOfBits#13]
`TypeError: "Argument 1 passed to BoxOfBits\tasks\BroadcastTask::__construct() must be an instance of BoxOfBits\tasks\BroadcastTask, instance of BoxOfBits\Loader given, called in /home/***/Desktop/PocketMine/plugins/BoxOfBits/Loader.php on line 53" (EXCEPTION) in "/BoxOfBits/src/BoxOfBits/tasks/BroadcastTask" at line 32`

Anyone know a fix or know why this is happening?

**Comment by Taki21** [comment]
That shall do xD

**Comment by dragonwocky** [comment]
Oh LOL, xD Thanks! 😃

**Comment by Taki21** [comment]
np
