### ISSUE TITLE
API Addition

### ISSUE THREAD

**Issue by dragonwocky** [BoxOfDevs/BoxOfBits#14]
Trying to add a working API system into BoxOfBits. Having a lot of trouble... Anyone have any experience with this type of stuff?

@iksaku I know you've done part of this on EssentialsPE, could you help if possible?

**Comment by applqpak** [comment]
@TheDragonRing just make some public functions..

**Comment by remotevase** [comment]
A lot of public functions will do the trick, keywords: a lot

**Comment by Taki21** [comment]
ME ME! ME WILL HELP

**Comment by remotevase** [comment]
XD LOL

**Comment by dragonwocky** [comment]
Ik but just using public functions is causing errors if I don't specify those public function in the file I'm running them from....

**Comment by iksaku** [comment]
@TheDragonRing Well, you can dig into EssentialsPE's code to see how our API is linked between files. Also our wiki has something useful for you to know :wink:

**Comment by Taki21** [comment]
@TheDragonRing U have us to help u fix em :)

**Comment by Taki21** [comment]
Make Public Functions and i can also give u MagicalAPI Src

**Comment by dragonwocky** [comment]
Thanks for all the help! I think I finally twisted my brain around, since I made a "working" system with the current files. Anyway, tomorrow I'll fiddle around and fix it all up in different files etc. Maybe also get started adding some other features too :)

**Comment by ghost** [comment]
lol

**Comment by Sandertv** [comment]
I know how to make/use API if you still need it...

**Comment by ghost** [comment]
What kind of API tho? I can make custom events

**Comment by dragonwocky** [comment]
@Sandertv I think I've got it covered, but I'll ask you for help if I need it
@KairusDarkSeeker not just custom events, I mean a full on API that can be accessed from any file in any plugin if they do it the correct way

**Comment by ghost** [comment]
Okay

**Comment by lavender-sys** [comment]
How do you make APIs in plugins??

**Comment by ghost** [comment]
@Dog2puppy make a class, getter of the class then kablah

**Comment by ghost** [comment]
@TheDragonRing breh what kind of api, I'll do it right away if you just tell me

**Comment by lavender-sys** [comment]
@KairusDarkSeeker I would assume a api to add, list, and remove broadcasts.

**Comment by ghost** [comment]
@Dog2puppy I'm asking Dragon not you

**Comment by dragonwocky** [comment]
by an API I mean something where a dev can basically modify all the things BoxOfBits does just from a couple of lines of code in another plugin. Anyway, I have a couple of ideas that I have tested and work for the API. Issue closed.
