### ISSUE TITLE
New Organization Icon

### ISSUE THREAD

**Issue by Taki21** [BoxOfDevs/BoxOfBits#15]
Ok Bad place to put this @TheDragonRing but here:
![www-otwarty-projekt](https://cloud.githubusercontent.com/assets/14851895/16137198/fc5c4240-33fe-11e6-9ccf-78080f0565ff.png)

**Comment by Taki21** [comment]
if u want a different icon let me know

**Comment by remotevase** [comment]
it's cool!

**Comment by remotevase** [comment]
but what's that curved line that's up near the top?

**Comment by Taki21** [comment]
not really sure...lel

**Comment by remotevase** [comment]
Oh, and thanks for the new Inactive-to-Reactive icon!

**Comment by Taki21** [comment]
np

**Comment by dragonwocky** [comment]
Cool but because of all the accounts etc that we have and it would take a while to redo everything maybe just have a new BoxOfBits icon?

**Comment by remotevase** [comment]
Good idea, this is for box of bits

**Comment by remotevase** [comment]
BoxofDevs should get a new icon that better suits the "devs" part

**Comment by Taki21** [comment]
Yup!

**Comment by Vaults1** [comment]
That line is too random. :P @remotevase maybe someone fixing a box? :P

**Comment by remotevase** [comment]
Hmm, maybe!

**Comment by lavender-sys** [comment]
@Taki21 How do you make icons so good??

**Comment by Taki21** [comment]
oh lol i found it on da internet but i can re edit it

**Comment by lavender-sys** [comment]
So you get all of your org icons from Google.

**Comment by ghost** [comment]
Just use a B icon with Brown and Mocha stripes

**Comment by ghost** [comment]
And do we have a Gitter or Twitter chat?

**Comment by Taki21** [comment]
@Dog2puppy pretty much

**Comment by lavender-sys** [comment]
So when you say your good at gfx on @MineralOS you mean your good at googling.

**Comment by Taki21** [comment]
no

**Comment by ghost** [comment]
Just ask @Mcsoldier12 on twitter
