### ISSUE TITLE
how i can join BoxOfDevs 

### ISSUE THREAD

**Issue by VCraftMCPE** [BoxOfDevs/BoxOfBits#16]

**Comment by VCraftMCPE** [comment]
i can its not a good place to ask

**Comment by VCraftMCPE** [comment]
i know its not a good place to ask

**Comment by ghost** [comment]
@VCraftMCPE be a good dev

**Comment by Taki21** [comment]
contribute more often using PRs

**Comment by dragonwocky** [comment]
Invited (he contacted me via Twitter)

**Comment by lavender-sys** [comment]
This can be closed then.
