### ISSUE TITLE
Question for @TheDragonRing

### ISSUE THREAD

**Issue by AvgZing** [BoxOfDevs/BoxOfBits#17]
Okay. I know BoxOfBits was born on January 25, 2016. When was BoxOfBits transferred to BoxOfDevs? I can go from there.

**Comment by AvgZing** [comment]
Never mind, I got it. How? I downloaded the Organization Audit log as json, used a date format converter [here](http://www.silisoftware.com/tools/date.php?inputdate=1459683692&inputformat=unix)
to convert this:
`{"actor":"TheDragonRing","org":"BoxOfDevs","action":"org.create","created_at":1459683692951}` into a date and time. Had to cut off the last 3 digits. It came up with
Sunday, April 3, 2016 11:41:32am UTC. Yay!

**Comment by dragonwocky** [comment]
Ok....
