### ISSUE TITLE
Filesystem/Class error

### ISSUE THREAD

**Issue by dragonwocky** [BoxOfDevs/BoxOfBits#3]
# Erm, help?

`[04:12:09] critical> ClassNotFoundException: "Class BoxOfBits\Loader not found" (EXCEPTION) in "/src/spl/BaseClassLoader" at line 144`

**Comment by applqpak** [comment]
You have class loader in the Loader.php, notice how yours is lowercase, but the error has uppercase.

**Comment by applqpak** [comment]
So in the plugin.yml you have:

`main: BoxOfBits\Loader`

In Laoder.php:

`class loader extends PluginBase {}` so change `class loader` to `class Loader`.

**Comment by applqpak** [comment]
Nevermind. I'll do it.

**Comment by applqpak** [comment]
Fixed.

**Comment by dragonwocky** [comment]
Thx!

**Comment by TheDragonRing** [comment]
Um how? You did make any commits...

**Comment by dragonwocky** [comment]
Still exact same error

**Comment by applqpak** [comment]
Shouldn't be.
