### ISSUE TITLE
should be commited in imagicalmine

### ISSUE THREAD

**Issue by MiroTheSuperDev** [BoxOfDevs/BoxOfBits#8]
we should commit this plugin to imagicalmine source code when its done that will make imagicalmine more famous and have more features

**Comment by dragonwocky** [comment]
Maybe, or maybe just add this plugin to the automatic IM download into the plugins folder, which would be even better because then if a player wants a more vanilla server they have an option to remove it

**Comment by remotevase** [comment]
yup, @TheDragonRing i like that idea better, personally

**Comment by dragonwocky** [comment]
I sent @keithkfng a conversation about it on the forums

**Comment by remotevase** [comment]
lol yeah.

**Comment by remotevase** [comment]
just noticed @AmiroEmad's new profile pic. Constantly changing it lol

**Comment by dragonwocky** [comment]
Lol yeah

**Comment by dragonwocky** [comment]
Could you have a look at #10 please?

**Comment by MiroTheSuperDev** [comment]
i have 25 avatars lol

**Comment by dragonwocky** [comment]
LOL seriously? I only have the one, and I just added the actual "DragonRing" to the face today :P
