### ISSUE TITLE
Add broadcastMessage and config

### ISSUE THREAD

**Issue by XakerS** [BoxOfDevs/BoxOfBits#9]
Bow particle,RegionGuard and WorldEdit Xd
I help you,send you code.

**Comment by dragonwocky** [comment]
Umm, you do realise this isn't done yet? I am adding config, and I may or may not add bow particle, region guard and world edit features - if I don't in this version I'll add them in the next version. I am also planning to add an automated broadcasting feature.

**Comment by XakerS** [comment]
Need help?

**Comment by dragonwocky** [comment]
Might later, but not yet, I'm still optimising the current stuff, once that's done I'll see if you can help. If you would like to join the organisation & contribute to the code please apply here - http://boxofdevs.x10host.com/apply

**Comment by dragonwocky** [comment]
> Need help?

Yeah the only new feature I'm adding is the auto broadcast feature, I'm going to leave the other stuff for next update. I'm not exactly sure how to do it tho.....

**Comment by dragonwocky** [comment]
See #10
